target 'MercadoLivreChallenge' do
  use_frameworks!

  pod 'Moya', '~> 13.0'
  pod 'Alamofire', '~> 4.1'
  pod 'Kingfisher', '= 4.9'
  pod 'R.swift'

  target 'MercadoLivreChallengeUnitTests' do
    pod 'Quick'
    pod 'Nimble'
  end

  target 'MercadoLivreChallengeTests' do
    pod 'KIF'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    pod 'Nimble'
    pod 'Quick'
  end
end
